import { Course, CourseLevel } from './types';

export const COURSES: Course[] = [
  {
    id: 'c1',
    title: 'Data Science Fundamentals',
    description: 'An introduction to the world of data science, covering statistics, probability, and basic Python programming.',
    outline: '<ul><li><strong>Week 1:</strong> Introduction to Data Science & Python Basics</li><li><strong>Week 2:</strong> Statistics and Probability Fundamentals</li><li><strong>Week 3:</strong> Data Manipulation with Pandas</li><li><strong>Week 4:</strong> Data Visualization with Matplotlib & Seaborn</li><li><strong>Week 5:</strong> Exploratory Data Analysis (EDA) Project</li><li><strong>Week 6:</strong> Introduction to Scikit-Learn</li><li><strong>Week 7:</strong> Basic Regression & Classification Models</li><li><strong>Week 8:</strong> Final Capstone Project</li></ul>',
    instructor: 'Dr. Sarah Chen',
    instructorBio: '<p>Dr. Sarah Chen is a Lead Data Scientist at a major tech firm with over 15 years of experience in statistical modeling and machine learning. She holds a Ph.D. in Statistics from Stanford University and is passionate about making complex data concepts accessible to beginners.</p>',
    duration: '8 Weeks',
    level: CourseLevel.BEGINNER,
    price: 499,
    tags: ['Python', 'Statistics', 'Data Analysis'],
    image: 'https://picsum.photos/id/1/800/600',
  },
  {
    id: 'c2',
    title: 'Advanced Machine Learning',
    description: 'Deep dive into neural networks, deep learning, and natural language processing using TensorFlow and PyTorch.',
    outline: '<ul><li><strong>Week 1-2:</strong> Neural Networks Foundations</li><li><strong>Week 3-4:</strong> Convolutional Neural Networks (CNNs)</li><li><strong>Week 5-6:</strong> Recurrent Neural Networks (RNNs) & LSTMs</li><li><strong>Week 7-8:</strong> Natural Language Processing (NLP) & Transformers</li><li><strong>Week 9-10:</strong> Generative Adversarial Networks (GANs)</li><li><strong>Week 11:</strong> Model Deployment & MLOps</li><li><strong>Week 12:</strong> Final Project Presentation</li></ul>',
    instructor: 'Prof. James Miller',
    instructorBio: '<p>Prof. James Miller is a Professor of Computer Science specializing in Artificial Intelligence. His research focuses on deep reinforcement learning and computer vision. He has published over 50 papers in top-tier AI conferences and consults for several AI startups.</p>',
    duration: '12 Weeks',
    level: CourseLevel.ADVANCED,
    price: 899,
    tags: ['AI', 'Machine Learning', 'TensorFlow'],
    image: 'https://picsum.photos/id/2/800/600',
  },
  {
    id: 'c3',
    title: 'Business Intelligence with Power BI',
    description: 'Learn to create stunning dashboards and actionable insights using Microsoft Power BI.',
    outline: '<ul><li><strong>Module 1:</strong> Connecting to Data Sources</li><li><strong>Module 2:</strong> Data Modeling and DAX Basics</li><li><strong>Module 3:</strong> Visualizing Data with Reports</li><li><strong>Module 4:</strong> Advanced Dashboards & Storytelling</li><li><strong>Module 5:</strong> Power BI Service & Sharing</li><li><strong>Module 6:</strong> Real-world Business Case Study</li></ul>',
    instructor: 'Emily Davis',
    instructorBio: '<p>Emily Davis is a certified Microsoft Data Analyst Associate and a Business Intelligence Consultant. She has helped numerous Fortune 500 companies transform their data into strategic assets using Power BI and Tableau.</p>',
    duration: '6 Weeks',
    level: CourseLevel.INTERMEDIATE,
    price: 399,
    tags: ['Power BI', 'Visualization', 'Business'],
    image: 'https://picsum.photos/id/3/800/600',
  },
  {
    id: 'c4',
    title: 'SQL for Data Analysis',
    description: 'Master the art of querying databases. Learn complex joins, window functions, and database optimization.',
    outline: '<ul><li><strong>Week 1:</strong> SQL Basics: SELECT, FROM, WHERE</li><li><strong>Week 2:</strong> Aggregations and Grouping</li><li><strong>Week 3:</strong> JOINS and Unions</li><li><strong>Week 4:</strong> Advanced: Window Functions & Subqueries</li></ul>',
    instructor: 'Michael Ross',
    instructorBio: '<p>Michael Ross is a Senior Backend Engineer with a decade of experience in database architecture. He specializes in SQL optimization and large-scale data systems. Michael believes that strong SQL skills are the foundation of any successful data career.</p>',
    duration: '4 Weeks',
    level: CourseLevel.BEGINNER,
    price: 299,
    tags: ['SQL', 'Database', 'Backend'],
    image: 'https://picsum.photos/id/4/800/600',
  },
  {
    id: 'c5',
    title: 'Predictive Analytics for Finance',
    description: 'Apply statistical algorithms and machine learning techniques to identify the likelihood of future financial outcomes.',
    outline: '<ul><li><strong>Week 1:</strong> Time Series Analysis Basics</li><li><strong>Week 2:</strong> ARIMA and SARIMA Models</li><li><strong>Week 3:</strong> Financial Risk Modeling</li><li><strong>Week 4:</strong> Monte Carlo Simulations</li><li><strong>Week 5:</strong> Algorithmic Trading Strategies</li><li><strong>Week 6-8:</strong> Forecasting Project</li></ul>',
    instructor: 'Robert Zhang',
    instructorBio: '<p>Robert Zhang is a Quantitative Analyst at a leading hedge fund. He applies advanced statistical methods and machine learning to financial markets. He holds an MSc in Financial Engineering and is an expert in time-series forecasting.</p>',
    duration: '10 Weeks',
    level: CourseLevel.ADVANCED,
    price: 750,
    tags: ['Finance', 'Forecasting', 'R'],
    image: 'https://picsum.photos/id/5/800/600',
  },
  {
    id: 'c6',
    title: 'Data Engineering Essentials',
    description: 'Learn how to build and maintain the infrastructure required for optimal extraction, transformation, and loading (ETL) of data.',
    outline: '<ul><li><strong>Week 1:</strong> Introduction to Data Engineering & Pipelines</li><li><strong>Week 2:</strong> SQL & NoSQL Databases for Big Data</li><li><strong>Week 3:</strong> Apache Spark & Hadoop Ecosystem</li><li><strong>Week 4:</strong> Cloud Data Warehousing (Snowflake/BigQuery)</li><li><strong>Week 5:</strong> ETL/ELT Processes with Airflow</li><li><strong>Week 6-10:</strong> Building an End-to-End Data Pipeline</li></ul>',
    instructor: 'Lisa Wong',
    instructorBio: '<p>Lisa Wong is a Principal Data Engineer who has built data platforms for unicorns in Silicon Valley. She has deep expertise in distributed systems, cloud computing (AWS/GCP), and big data technologies like Spark and Kafka.</p>',
    duration: '10 Weeks',
    level: CourseLevel.INTERMEDIATE,
    price: 650,
    tags: ['ETL', 'Big Data', 'Cloud'],
    image: 'https://picsum.photos/id/6/800/600',
  }
];