-- Create profiles table
create table if not exists profiles (
  id uuid references auth.users not null primary key,
  name text,
  email text,
  role text default 'student',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create courses table
create table if not exists courses (
  id text primary key,
  title text not null,
  description text,
  outline text,
  instructor text,
  instructor_bio text,
  duration text,
  level text,
  price numeric,
  tags text[],
  image text,
  signature_image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create enrollments table
create table if not exists enrollments (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  course_id text references courses(id) not null,
  status text default 'registered',
  progress numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, course_id)
);

-- Create site_settings table
create table if not exists site_settings (
  key text primary key,
  value jsonb
);

-- Create videos table
create table if not exists videos (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  duration text,
  type text,
  level text,
  category text,
  url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table profiles enable row level security;
alter table courses enable row level security;
alter table enrollments enable row level security;
alter table site_settings enable row level security;
alter table videos enable row level security;

-- Policies

-- Profiles
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- Courses
create policy "Courses are viewable by everyone." on courses for select using (true);
create policy "Admins can insert courses." on courses for insert with check (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can update courses." on courses for update using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can delete courses." on courses for delete using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- Enrollments
create policy "Users can view own enrollments." on enrollments for select using (auth.uid() = user_id);
create policy "Admins can view all enrollments." on enrollments for select using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));
create policy "Users can insert own enrollments." on enrollments for insert with check (auth.uid() = user_id);
create policy "Users can update own enrollments." on enrollments for update using (auth.uid() = user_id);
create policy "Admins can update enrollments." on enrollments for update using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- Site Settings
create policy "Site settings are viewable by everyone." on site_settings for select using (true);
create policy "Admins can update site settings." on site_settings for update using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can insert site settings." on site_settings for insert with check (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- Videos
create policy "Videos are viewable by everyone." on videos for select using (true);
create policy "Admins can insert videos." on videos for insert with check (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

-- Trigger for new users
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, name, email, role)
  values (new.id, new.raw_user_meta_data->>'name', new.email, 'student');
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Storage Setup
insert into storage.buckets (id, name, public)
values ('app-files', 'app-files', true)
on conflict (id) do nothing;

-- Storage Policies
-- Note: You may need to enable RLS on storage.objects if not already enabled
alter table storage.objects enable row level security;

create policy "Public Read" on storage.objects for select using ( bucket_id = 'app-files' );
create policy "Authenticated Upload" on storage.objects for insert with check ( bucket_id = 'app-files' and auth.role() = 'authenticated' );
create policy "Users Update Own Files" on storage.objects for update using ( bucket_id = 'app-files' and auth.uid()::text = (storage.foldername(name))[1] );
create policy "Users Delete Own Files" on storage.objects for delete using ( bucket_id = 'app-files' and auth.uid()::text = (storage.foldername(name))[1] );

-- Seed Data for Courses
insert into courses (id, title, description, outline, instructor, instructor_bio, duration, level, price, tags, image)
values
  ('c1', 'Data Science Fundamentals', 'An introduction to the world of data science, covering statistics, probability, and basic Python programming.', '<ul><li><strong>Week 1:</strong> Introduction to Data Science & Python Basics</li><li><strong>Week 2:</strong> Statistics and Probability Fundamentals</li><li><strong>Week 3:</strong> Data Manipulation with Pandas</li><li><strong>Week 4:</strong> Data Visualization with Matplotlib & Seaborn</li><li><strong>Week 5:</strong> Exploratory Data Analysis (EDA) Project</li><li><strong>Week 6:</strong> Introduction to Scikit-Learn</li><li><strong>Week 7:</strong> Basic Regression & Classification Models</li><li><strong>Week 8:</strong> Final Capstone Project</li></ul>', 'Dr. Sarah Chen', '<p>Dr. Sarah Chen is a Lead Data Scientist at a major tech firm with over 15 years of experience in statistical modeling and machine learning. She holds a Ph.D. in Statistics from Stanford University and is passionate about making complex data concepts accessible to beginners.</p>', '8 Weeks', 'Beginner', 499, ARRAY['Python', 'Statistics', 'Data Analysis'], 'https://picsum.photos/id/1/800/600'),
  ('c2', 'Advanced Machine Learning', 'Deep dive into neural networks, deep learning, and natural language processing using TensorFlow and PyTorch.', '<ul><li><strong>Week 1-2:</strong> Neural Networks Foundations</li><li><strong>Week 3-4:</strong> Convolutional Neural Networks (CNNs)</li><li><strong>Week 5-6:</strong> Recurrent Neural Networks (RNNs) & LSTMs</li><li><strong>Week 7-8:</strong> Natural Language Processing (NLP) & Transformers</li><li><strong>Week 9-10:</strong> Generative Adversarial Networks (GANs)</li><li><strong>Week 11:</strong> Model Deployment & MLOps</li><li><strong>Week 12:</strong> Final Project Presentation</li></ul>', 'Prof. James Miller', '<p>Prof. James Miller is a Professor of Computer Science specializing in Artificial Intelligence. His research focuses on deep reinforcement learning and computer vision. He has published over 50 papers in top-tier AI conferences and consults for several AI startups.</p>', '12 Weeks', 'Advanced', 899, ARRAY['AI', 'Machine Learning', 'TensorFlow'], 'https://picsum.photos/id/2/800/600'),
  ('c3', 'Business Intelligence with Power BI', 'Learn to create stunning dashboards and actionable insights using Microsoft Power BI.', '<ul><li><strong>Module 1:</strong> Connecting to Data Sources</li><li><strong>Module 2:</strong> Data Modeling and DAX Basics</li><li><strong>Module 3:</strong> Visualizing Data with Reports</li><li><strong>Module 4:</strong> Advanced Dashboards & Storytelling</li><li><strong>Module 5:</strong> Power BI Service & Sharing</li><li><strong>Module 6:</strong> Real-world Business Case Study</li></ul>', 'Emily Davis', '<p>Emily Davis is a certified Microsoft Data Analyst Associate and a Business Intelligence Consultant. She has helped numerous Fortune 500 companies transform their data into strategic assets using Power BI and Tableau.</p>', '6 Weeks', 'Intermediate', 399, ARRAY['Power BI', 'Visualization', 'Business'], 'https://picsum.photos/id/3/800/600'),
  ('c4', 'SQL for Data Analysis', 'Master the art of querying databases. Learn complex joins, window functions, and database optimization.', '<ul><li><strong>Week 1:</strong> SQL Basics: SELECT, FROM, WHERE</li><li><strong>Week 2:</strong> Aggregations and Grouping</li><li><strong>Week 3:</strong> JOINS and Unions</li><li><strong>Week 4:</strong> Advanced: Window Functions & Subqueries</li></ul>', 'Michael Ross', '<p>Michael Ross is a Senior Backend Engineer with a decade of experience in database architecture. He specializes in SQL optimization and large-scale data systems. Michael believes that strong SQL skills are the foundation of any successful data career.</p>', '4 Weeks', 'Beginner', 299, ARRAY['SQL', 'Database', 'Backend'], 'https://picsum.photos/id/4/800/600'),
  ('c5', 'Predictive Analytics for Finance', 'Apply statistical algorithms and machine learning techniques to identify the likelihood of future financial outcomes.', '<ul><li><strong>Week 1:</strong> Time Series Analysis Basics</li><li><strong>Week 2:</strong> ARIMA and SARIMA Models</li><li><strong>Week 3:</strong> Financial Risk Modeling</li><li><strong>Week 4:</strong> Monte Carlo Simulations</li><li><strong>Week 5:</strong> Algorithmic Trading Strategies</li><li><strong>Week 6-8:</strong> Forecasting Project</li></ul>', 'Robert Zhang', '<p>Robert Zhang is a Quantitative Analyst at a leading hedge fund. He applies advanced statistical methods and machine learning to financial markets. He holds an MSc in Financial Engineering and is an expert in time-series forecasting.</p>', '10 Weeks', 'Advanced', 750, ARRAY['Finance', 'Forecasting', 'R'], 'https://picsum.photos/id/5/800/600'),
  ('c6', 'Data Engineering Essentials', 'Learn how to build and maintain the infrastructure required for optimal extraction, transformation, and loading (ETL) of data.', '<ul><li><strong>Week 1:</strong> Introduction to Data Engineering & Pipelines</li><li><strong>Week 2:</strong> SQL & NoSQL Databases for Big Data</li><li><strong>Week 3:</strong> Apache Spark & Hadoop Ecosystem</li><li><strong>Week 4:</strong> Cloud Data Warehousing (Snowflake/BigQuery)</li><li><strong>Week 5:</strong> ETL/ELT Processes with Airflow</li><li><strong>Week 6-10:</strong> Building an End-to-End Data Pipeline</li></ul>', 'Lisa Wong', '<p>Lisa Wong is a Principal Data Engineer who has built data platforms for unicorns in Silicon Valley. She has deep expertise in distributed systems, cloud computing (AWS/GCP), and big data technologies like Spark and Kafka.</p>', '10 Weeks', 'Intermediate', 650, ARRAY['ETL', 'Big Data', 'Cloud'], 'https://picsum.photos/id/6/800/600')
on conflict (id) do nothing;
